# Alvo: dependecias
# 	comandos
# Primeiro executa a dependencia e depois o alvo

script= hello.py

run:
	@python $(script)

print-world: print-hello
	@echo "world"

print-hello:
	@echo "hello"

# build:
# 	@python run.py